package pw.spn.idealista.model.home;

public enum HomeAmenity {
    GARAGE, ELEVATOR, SWIMMING_POOL, AIR_CONDITIONING, TERRANCE, STORE_ROOM, CLOTHESLINE_SPACE, BUILTIN_WARDROBES,
    INDEPENDENT_HOT_WATER, INDEPENDENT_HEATING;
}
